EmployCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from tasks.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('students/', include('students.urls', namespace="students")),
    path('colleges/', include('colleges.urls', namespace="colleges")),
    path('admin-signup/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

students/urls.py
from django.urls import path
from .views import (
    StudentCreateView,
    StudentDeleteView,
    StudentDetailView,
    StudentListView,
    StudentUpdateView,
    UploadStudents
)

app_name = "students"

urlpatterns = [
    path('', StudentListView.as_view(), name='student-list'),
    path('<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
    path('<int:pk>/update/', StudentUpdateView.as_view(), name='student-update'),
    path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student-delete'),
    path('create/', StudentCreateView.as_view(), name='student-create'),
    path('upload_students/', UploadStudents.as_view(), name='upload-students'),
]

tasks/urls.py
from django.urls import path
from .views import (
    TaskCreateView, TaskDeleteView, TaskDetailView, TaskUpdateView, TaskListView
)

app_name = "tasks"

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('create/', TaskCreateView.as_view(), name='task-create')
]

students/models.py
from django.db import models

# Create your models here.

students/forms.py
from django import forms
from django import forms
from django.contrib.auth import get_user_model

from tasks.models import Student


User = get_user_model()


profile_choices = (
    ("Developer", "Developer"),
    ("AI", "AI")
)


class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            'first_name',
            'last_name',
            'phone_number',
            'email',
            'college_name',
            'college_roll_number',
            'profile',
            'assigned_to',
            'joining_date',
            'offer_letter_issue_date',
            'completion_letter_issue_date',
            # 'is_updated',
            'is_offer_letter_issued',
            'is_completion_letter_issued'
        )
        widgets = {
            'joining_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
            'offer_letter_issue_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
            'completion_letter_issue_date': forms.DateInput(format=('%Y-%m-%d'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
            # 'Profile': forms.MultipleChoiceField(choices=profile_choices)
        }


class NewStudentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'phone_number',
            'email'
        )
        labels = {
            "username": "roll number"
        }

students/views.py
import csv
import io
from builtins import next, Exception

from django.contrib.auth import get_user_model
from django.shortcuts import render, reverse,redirect
from django.views import generic
from .mixins import AdminAndLoginRequiredMixin
from django.contrib import messages


from tasks.models import Student
from .forms import NewStudentModelForm, StudentModelForm

User = get_user_model()

class StudentListView(AdminAndLoginRequiredMixin, generic.ListView):
    template_name = "students/student_list.html"

    def get_queryset(self):
        return Student.objects.all()


class StudentCreateView(AdminAndLoginRequiredMixin, generic.CreateView):
    template_name = "students/student_create.html"
    form_class = NewStudentModelForm

    def get_success_url(self):
        return reverse("students:student-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_admin = False
        user.set_password(user.phone_number)
        user.save()

        Student.objects.create(
            user=user,
            first_name=user.first_name,
            last_name=user.last_name,
            phone_number=user.phone_number,
            email=user.email,
            college_roll_number=user.username
        )

        return super(StudentCreateView, self).form_valid(form)

class UploadStudents(AdminAndLoginRequiredMixin, generic.CreateView):
    def get(self, request):
        template="students/upload_students.html"
        context={
            'file_description': 'Order of CSV fil should be First Name, Last Name, Roll Number, Phone Number, Email Address.'
        }
        return render(request,template,context)
    def post(self,request):
        template = "students/upload_students.html"
        try:
            csv_file = request.FILES['file']
            if not csv_file.name.endswith('.csv'):
                messages.error(request, 'THIS IS NOT A CSV FILE')
            try:
                data_set = csv_file.read().decode('UTF-8')
                io_string = io.StringIO(data_set)
                next(io_string)
                for data in csv.reader(io_string, delimiter=',', quotechar="|"):
                    user = User(
                        username=data[2],
                        first_name=data[0],
                        last_name=data[1],
                        phone_number=data[3],
                        email=data[4],
                    )
                    user.is_admin=False
                    user.set_password(user.phone_number)
                    user.save()
                    _, created = Student.objects.update_or_create(
                        user=user,
                        first_name=data[0],
                        last_name=data[1],
                        phone_number=data[3],
                        email=data[4],
                        college_roll_number=data[2],
                    )
                messages.error(request,"Your data")
                return reverse("students:student-list")
            except Exception as e:
                messages.error(request, e)
                return render(request,template)
        except:
            messages.error(request,"Choose a CSV File.")
            return render(request,template)

class StudentDetailView(AdminAndLoginRequiredMixin, generic.DetailView):
    template_name = "students/student_detail.html"
    context_object_name = "student"

    def get_queryset(self):
        return Student.objects.all()


class StudentUpdateView(AdminAndLoginRequiredMixin, generic.UpdateView):
    template_name = "students/student_update.html"
    form_class = StudentModelForm

    def get_queryset(self):
        return Student.objects.all()

    def get_success_url(self):
        return reverse("students:student-list")


class StudentDeleteView(AdminAndLoginRequiredMixin, generic.DeleteView):
    template_name = "students/student_delete.html"
    context_object_name = "student"

    def get_queryset(self):
        return Student.objects.all()

    def get_success_url(self):
        return reverse("students:student-list")

students/templates/students/completion_certificate.html
{% extends 'completion_certificate_template.html' %}
{% block content %}
{%if not request_for_completion_certificate %}
        <form action="" method="post">
            {%csrf_token%}
            <input type="submit" value="Request For Completion Certificate">
        </form>
    {%else%}
        <form action="" method="post">
            {%csrf_token%}
            <input type="submit" value="Download Completion Certificate.">
        </form>
    {%endif%}
    {% if message %}
        <script>
                window.onload=function(){
                    alert('{{message}}')
                }
        </script>
    {% endif %}
{% endblock %}

students/templates/students/offer_letter.html
{% extends 'offer_letter_template.html' %}
{% block content %}
{%if not employee.request_for_offer_letter %}
        <div>
            <p>
                I hereby declare that the details furnished above are true and correct to the best of my knowledge and belief. Also, I hereby agree to abide by the terms and conditions provided above.
                I allow company to take necessary measures incase I am found in breach of the mentioned clauses.
                I Formally give my consent to Medicento & YoursBiz to keep my personal information after the date of application and consider my profile for any further opportunities.
            </p>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="acknowledge">
                <input type="checkbox" name="check-acknowledge" id="check-acknowledge" required checked>
                <label for="check-acknowledge">I hereby acknowledge that I had read all the terms and conditions properly and accept all the terms
                    and conditions</label>
                <br/>
                <br/>
            </div>
            <input type="submit" value="Request For Offer Letter">
        </form>
    {% else %}
        <form action="" method="post">
            {%csrf_token%}
            <input type="submit" value="Download Offer Letter.">
        </form>
    {%endif%}
    {% if message %}
        <script>
                window.onload=function(){
                    alert('{{message}}')
                }
        </script>
    {% endif %}
{% endblock %}

students/templates/students/student_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'students:student-list' %}">Go back to students</a>
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-700">Add a new student</h1>
        </div>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

students/templates/students/student_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'students:student-list' %}">Go back to students</a>
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-700">Are you sure you want to delete this student?</h1>
        </div>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                YES
            </button>
        </form>
    </div>
{% endblock content %}

students/templates/students/student_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-3/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">STUDENT</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ student.first_name }} {{ student.last_name }}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
          <a href="{% url 'students:student-update' student.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 pr-5">Phone Number</span>
          <span class="ml-auto text-gray-900">{{ student.phone_number }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 pr-5">Email</span>
          <span class="ml-auto text-gray-900">{{ student.email }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500 pr-5">Roll Number</span>
          <span class="ml-auto text-gray-900">{{ student.college_roll_number }}</span>
        </div>
        <div class="flex">
            <a href="{% url 'students:student-delete' student.pk %}" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                Delete Student
            </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
    

students/templates/students/student_list.html
{% extends 'base.html' %}

{% block content %}
    <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Students</h1>
        </div>
        <div>
            <a class="text-gray-500 hover:text-blue-500" href="{% url 'students:student-create' %}">add student</a>
            <a class="text-gray-500 hover:text-blue-500" href="{% url 'students:upload-students' %}">Upload Student</a>
        </div>
        </div>
        <div class="flex flex-wrap -m-4">
        {% for student in object_list %}
            <div class="p-4 lg:w-1/2 md:w-full">
            <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                </svg>
                </div>
                <div class="flex-grow">
                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Name : {{ student.first_name }} {{ student.last_name }}</h2>
                <p class="leading-relaxed text-base">
                    email : {{ student.email }}
                </p>
                <a href="{% url 'students:student-detail' student.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                    View Student
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </a>
                </div>
            </div>
            </div>
        {% endfor %}
        </div>
    </div>
    </section>
{% endblock content %}

students/templates/students/student_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">STUDENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ task.task_name }}</h1>
            <div class="flex mb-4">
            <a href="{% url 'students:student-detail' student.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Update</button>
            </from>
        </div>
    </div>
    </section>
{% endblock content %}
    

students/templates/students/upload_students.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'students:student-list' %}">Go back to students</a>
        {{order}}
        {% if messages %}
            {% for message in messages %}
                <div>
    <!--                | means OR operator-->
                    <strong>{{message|safe}}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-700">Upload Students in CSV format</h1>
        </div>
        <form action="" method="POST" enctype="multipart/form-data" id="upload_students">
        {% csrf_token %}
        <label for="file1"> Upload a file</label>
            <hr></hr>
        <input type="file"  id="file1" name="file">
            <hr></hr>
        <label>Only accepts CSV files</label>
            <hr></hr>
        <button type="submit">Upload</button>
    </form>
</div>
{% endblock content %}