EmployCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from tasks.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('students/', include('students.urls', namespace="students")),
    path('colleges/', include('colleges.urls', namespace="colleges")),
    path('admin-signup/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/urls.py
from django.urls import path
from .views import (
    TaskCreateView, TaskDeleteView, TaskDetailView, TaskUpdateView, TaskListView
)

app_name = "tasks"

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('create/', TaskCreateView.as_view(), name='task-create')
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


PROFILE_CHOICES = (
    ('Developer', 'Developer'),
    ('AI', 'AI'),
)

ASSIGNED_TO_CHOICES = (
    ('Rekha', 'Rekha'),
    ('test', 'test'),
)


class User(AbstractUser):
    is_admin = models.BooleanField(default=True)
    phone_number = models.CharField(max_length=10)


class Task(models.Model):
    project_name = models.CharField(max_length=100)
    task_name = models.CharField(max_length=200)
    student = models.ForeignKey("Student", null=True, blank=True, on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return f"{self.project_name} : {self.task_name}"


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(blank=True, max_length=100, default='')
    phone_number = models.CharField(max_length=10)
    email = models.EmailField()
    college_name = models.ForeignKey("College" ,blank=True, null=True, on_delete=models.SET_NULL)
    college_roll_number = models.CharField(max_length=20)
    profile = models.CharField(max_length=100, choices=PROFILE_CHOICES)
    assigned_to = models.CharField(max_length=100, choices=ASSIGNED_TO_CHOICES)
    joining_date = models.DateField(blank=True, null=True)
    offer_letter_issue_date = models.DateField(blank=True, null=True)
    completion_letter_issue_date = models.DateField(blank=True, null=True)
    is_updated = models.BooleanField("is_updated", default=False)
    is_offer_letter_issued = models.BooleanField("is_offer_letter_issued", default=False)
    is_completion_letter_issued = models.BooleanField("is_completion_letter_issued", default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.college_roll_number}"


class College(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

    def __str__(self):
        return self.name

tasks/forms.py
from django import forms
from django.forms import fields
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import Task

User = get_user_model()


class TaskModelForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = (
            'project_name',
            'task_name',
            'description',
        )


class TaskForm(forms.Form):
    project_name = forms.CharField(max_length=100)
    task_name = forms.CharField(max_length=200)
    description = forms.CharField(max_length=1000)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

tasks/views.py
from django import contrib
from django.contrib import messages
from django.core.mail import send_mail
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import generic

from .models import Task, Student
from .forms import TaskForm, TaskModelForm, CustomUserCreationForm


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class TaskListView(LoginRequiredMixin, generic.ListView):
    template_name = "tasks/task_list.html"
    context_object_name = "tasks"

    def get_queryset(self):
        queryset = Task.objects.all()
        if not self.request.user.is_admin:
            queryset = queryset.filter(student__user = self.request.user)
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "tasks/task_detail.html"
    context_object_name = "task"

    def get_queryset(self):
        queryset = Task.objects.all()
        if not self.request.user.is_admin:
            queryset = queryset.filter(student__user = self.request.user)
        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "tasks/task_create.html"
    form_class = TaskModelForm

    def get_success_url(self):
        return reverse("tasks:task-list")

    def form_valid(self, form):
        task = form.save(commit=False)
        task.student = Student.objects.get(user=self.request.user)
        task.save()
        return super(TaskCreateView, self).form_valid(form)


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "tasks/task_update.html"
    form_class = TaskModelForm

    def get_queryset(self):
        queryset = Task.objects.all()
        if not self.request.user.is_admin:
            queryset = queryset.filter(student__user = self.request.user)
        return queryset

    def get_success_url(self):
        return reverse("tasks:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = "tasks/task_delete.html"

    def get_queryset(self):
        queryset = Task.objects.all()
        if not self.request.user.is_admin:
            queryset = queryset.filter(student__user = self.request.user)
        return queryset

    def get_success_url(self):
        return reverse("tasks:task-list")

tasks/templates/tasks/task_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'tasks:task-list' %}">Go back to tasks</a>
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-700">Create a new task</h1>
        </div>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

tasks/templates/tasks/task_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'tasks:task-list' %}">Go back to tasks</a>
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-700">Are you sure you want to delete this task?</h1>
        </div>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                YES
            </button>
        </form>
    </div>
{% endblock content %}

tasks/templates/tasks/task_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-3/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">TASK</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ task.task_name }}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
          <a href="{% url 'tasks:task-update' task.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 pr-5">Project name</span>
          <span class="ml-auto text-gray-900">{{ task.project_name }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 pr-5">Task name</span>
          <span class="ml-auto text-gray-900">{{ task.task_name }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500 pr-5">Description</span>
          <span class="ml-auto text-gray-900">{{ task.description }}</span>
        </div>
        <div class="flex">
            <a href="{% url 'tasks:task-delete' task.pk %}" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                Delete Task
            </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
    

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div>
        <h1 class="text-4xl text-gray-800">Tasks</h1>
      </div>
      {% if not request.user.is_admin %}
        <div>
          <a class="text-gray-500 hover:text-blue-500" href="{% url 'tasks:task-create' %}">create task</a>
        </div>
      {% endif %}
    </div>
    <div class="flex flex-wrap -m-4">
      {% for task in tasks %}
        <div class="p-4 lg:w-full md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Project : {{ task.project_name }}</h2>
              <p class="leading-relaxed text-base">
                Task name : {{ task.task_name }}
              </p>
              <a href="{% url 'tasks:task-detail' task.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                View Task
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}
  

tasks/templates/tasks/task_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">TASK</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ task.task_name }}</h1>
            <div class="flex mb-4">
            <a href="{% url 'tasks:task-detail' task.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Update</button>
            </from>
        </div>
    </div>
    </section>
{% endblock content %}
    