EmployCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from tasks.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('tasks/', include('tasks.urls', namespace="tasks")),
    path('students/', include('students.urls', namespace="students")),
    path('colleges/', include('colleges.urls', namespace="colleges")),
    path('admin-signup/', SignupView.as_view(), name="signup"),
    path('logout/', LogoutView.as_view(), name="logout")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

colleges/urls.py
from colleges.views import CollegeCreateView, CollegeDeleteView, CollegeDetailView, CollegeListView, CollegeUpdateView
from django.urls import path

app_name = "colleges"

urlpatterns = [
    path('', CollegeListView.as_view(), name='college-list'),
    path('<int:pk>/', CollegeDetailView.as_view(), name='college-detail'),
    path('<int:pk>/update/', CollegeUpdateView.as_view(), name='college-update'),
    path('<int:pk>/delete/', CollegeDeleteView.as_view(), name='college-delete'),
    path('create/', CollegeCreateView.as_view(), name='college-create'),
]

tasks/urls.py
from django.urls import path
from .views import (
    TaskCreateView, TaskDeleteView, TaskDetailView, TaskUpdateView, TaskListView
)

app_name = "tasks"

urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('<int:pk>/', TaskDetailView.as_view(), name='task-detail'),
    path('<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('create/', TaskCreateView.as_view(), name='task-create')
]

colleges/models.py
from django.db import models

# Create your models here.

colleges/forms.py
from django import forms
from tasks.models import College


class CollegeModelForm(forms.ModelForm):
    class Meta:
        model = College
        fields = (
            'name',
            'city',
            'state'
        )

colleges/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, reverse
from django.views import generic
from students.mixins import AdminAndLoginRequiredMixin

from tasks.models import College
from .forms import CollegeModelForm

User = get_user_model()

class CollegeListView(AdminAndLoginRequiredMixin, generic.ListView):
    template_name = "colleges/college_list.html"

    def get_queryset(self):
        return College.objects.all()


class CollegeCreateView(AdminAndLoginRequiredMixin, generic.CreateView):
    template_name = "colleges/college_create.html"
    form_class = CollegeModelForm

    def get_success_url(self):
        return reverse("colleges:college-list")


class CollegeDetailView(AdminAndLoginRequiredMixin, generic.DetailView):
    template_name = "colleges/college_detail.html"
    context_object_name = "college"

    def get_queryset(self):
        return College.objects.all()


class CollegeUpdateView(AdminAndLoginRequiredMixin, generic.UpdateView):
    template_name = "colleges/college_update.html"
    form_class = CollegeModelForm

    def get_queryset(self):
        return College.objects.all()

    def get_success_url(self):
        return reverse("colleges:college-list")


class CollegeDeleteView(AdminAndLoginRequiredMixin, generic.DeleteView):
    template_name = "colleges/college_delete.html"
    context_object_name = "college"

    def get_queryset(self):
        return College.objects.all()

    def get_success_url(self):
        return reverse("colleges:college-list")

colleges/templates/colleges/college_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'colleges:college-list' %}">Go back to colleges</a>
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-700">Add a college</h1>
        </div>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                Submit
            </button>
        </form>
    </div>
{% endblock content %}

colleges/templates/colleges/college_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <a class="hover:text-blue-500" href="{% url 'colleges:college-list' %}">Go back to colleges</a>
        <div class="py-5 border-t border-gray-200">
            <h1 class="text-4xl text-gray-700">Are you sure you want to delete this college?</h1>
        </div>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                YES
            </button>
        </form>
    </div>
{% endblock content %}

colleges/templates/colleges/college_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-3/5 mx-auto flex flex-wrap">
      <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">COLLEGE</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ college.name }}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Details</a>
          <a href="{% url 'colleges:college-update' college.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 pr-5">Name</span>
          <span class="ml-auto text-gray-900">{{ college.name }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500 pr-5">City</span>
          <span class="ml-auto text-gray-900">{{ college.city }}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500 pr-5">State</span>
          <span class="ml-auto text-gray-900">{{ college.state }}</span>
        </div>
        <div class="flex">
            <a href="{% url 'colleges:college-delete' college.pk %}" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                Delete College
            </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}
    

colleges/templates/colleges/college_list.html
{% extends 'base.html' %}

{% block content %}
    <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
            <h1 class="text-4xl text-gray-800">Colleges</h1>
        </div>
        <div>
            <a class="text-gray-500 hover:text-blue-500" href="{% url 'colleges:college-create' %}">add college</a>
        </div>
        </div>
        <div class="flex flex-wrap -m-4">
        {% for college in object_list %}
            <div class="p-4 lg:w-1/2 md:w-full">
            <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                </svg>
                </div>
                <div class="flex-grow">
                <h2 class="text-gray-900 text-lg title-font font-medium mb-3">Name : {{ college.name }}</h2>
                <p class="leading-relaxed text-base">
                    City : {{ college.city }}
                </p>
                <a href="{% url 'colleges:college-detail' college.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                    View College
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </a>
                </div>
            </div>
            </div>
        {% endfor %}
        </div>
    </div>
    </section>
{% endblock content %}

colleges/templates/colleges/college_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
    <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">COLLEGE</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ task.task_name }}</h1>
            <div class="flex mb-4">
            <a href="{% url 'colleges:college-detail' college.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Details</a>
            <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Update</button>
            </from>
        </div>
    </div>
    </section>
{% endblock content %}
    